version: '2'
services:
 parity-local:
   image: ethcore/parity:v1.6.6
   working_dir: /parity/
   command: --jsonrpc-interface all --jsonrpc-hosts all --jsonrpc-cors * --dapps-interface 0.0.0.0 --dapps-hosts all --ui-interface 0.0.0.0 --ui-no-validation --chain dev
   ports:
     - 8545:8545
     - 8080:8080
     - 8180:8180
   volumes:
     - ./paritydata:/root/.local
