version: '2'
services:
 parity-local:
   image: parity/parity:v1.7.2
   working_dir: /parity/
   command: --jsonrpc-interface all --jsonrpc-cors * --ui-interface all --ws-interface all --ws-origins all --chain dev
   ports:
     - 8545:8545
     - 8546:8546
     - 8180:8180
   volumes:
     - ./paritydata:/root/.local
